name: Run Mineflayer Bot

on:
  workflow_dispatch:
  push:
  schedule:
    - cron: "*/20 * * * *"

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Repo İndir
        uses: actions/checkout@v3

      - name: Node Kur
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Bağımlılıkları Yükle
        run: npm install

      - name: Botu Çalıştır
        run: node index.js
